obj/./manager/game_state_run.o: manager/game_state_run.cpp \
 manager/game_state_run.h manager/manager.h manager/../cube.h \
 manager/../libs/math.h manager/../libs/image.h manager/../libs/time.h \
 manager/../libs/structure.h manager/../libs/math.h \
 manager/../libs/color.h manager/../libs/color.h \
 manager/../libs/exception.h manager/../libs/xb_cube.h \
 manager/../libs/common.h
obj/./manager/manager.o: manager/manager.cpp manager/manager.h \
 manager/game_state_run.h manager/../cube.h manager/../libs/math.h \
 manager/../libs/image.h manager/../libs/time.h \
 manager/../libs/structure.h manager/../libs/math.h \
 manager/../libs/color.h manager/../libs/color.h \
 manager/../libs/exception.h manager/../libs/xb_cube.h \
 manager/../libs/common.h
obj/./main.o: main.cpp cube.h libs/math.h libs/image.h libs/time.h \
 libs/structure.h libs/math.h libs/color.h libs/color.h libs/exception.h \
 libs/xb_cube.h libs/common.h manager/manager.h manager/game_state_run.h \
 manager/manager.h manager/../cube.h
obj/./libs/image.o: libs/image.cpp libs/image.h
obj/./libs/math.o: libs/math.cpp libs/math.h
obj/./libs/xb_cube.o: libs/xb_cube.cpp libs/xb_cube.h
obj/./libs/color.o: libs/color.cpp libs/color.h
obj/./libs/structure.o: libs/structure.cpp libs/structure.h libs/math.h \
 libs/color.h
obj/./libs/time.o: libs/time.cpp libs/time.h
obj/./libs/common.o: libs/common.cpp libs/common.h
obj/./libs/config.o: libs/config.cpp libs/config.h
obj/./libs/exception.o: libs/exception.cpp libs/exception.h
